// verses.js - VerseTap content pool (NIV). Generated by tools/fetch_verses.py.
// BIBLE_BOOKS: the 66-book canon in order (index 0 = Genesis). VERSE_TIERS: 5 tiers
// x 24 verses, one tier per round, easy -> hard. Entry: {book, ref, context, text}
// where `book` is the 1-based canon position. See README for the NIV copyright notice.
const BIBLE_BOOKS = ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy", "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Songs", "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi", "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians", "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation"];
const VERSE_TIERS = [
 {
  "label": "Well-Worn Verses",
  "verses": [
   {
    "book": 43,
    "ref": "John 3:16",
    "context": "The gospel in one sentence, spoken to Nicodemus at night.",
    "text": "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life."
   },
   {
    "book": 19,
    "ref": "Psalm 23:1",
    "context": "David's shepherd psalm opens with the whole point.",
    "text": "The Lord is my shepherd, I shall not be in want."
   },
   {
    "book": 50,
    "ref": "Philippians 4:13",
    "context": "Paul's secret of contentment, written from a Roman prison.",
    "text": "I can do everything through him who gives me strength."
   },
   {
    "book": 45,
    "ref": "Romans 8:28",
    "context": "A promise for those who love God, even in the mess.",
    "text": "More Than Conquerors And we know that in all things God works for the good of those who love him, who have been called according to his purpose."
   },
   {
    "book": 1,
    "ref": "Genesis 1:1",
    "context": "The first words of the Bible.",
    "text": "The Beginning In the beginning God created the heavens and the earth."
   },
   {
    "book": 20,
    "ref": "Proverbs 3:5-6",
    "context": "Solomon's most-quoted advice on decision-making.",
    "text": "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways acknowledge him, and he will make your paths straight."
   },
   {
    "book": 24,
    "ref": "Jeremiah 29:11",
    "context": "Written to exiles in Babylon, with seventy years still to go.",
    "text": "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future."
   },
   {
    "book": 40,
    "ref": "Matthew 28:19",
    "context": "The Great Commission, given on a mountain in Galilee.",
    "text": "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,"
   },
   {
    "book": 23,
    "ref": "Isaiah 40:31",
    "context": "Comfort for a weary nation: eagles, running, walking.",
    "text": "but those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."
   },
   {
    "book": 6,
    "ref": "Joshua 1:9",
    "context": "God's charge to Joshua right after Moses died.",
    "text": "Have I not commanded you? Be strong and courageous. Do not be terrified; do not be discouraged, for the Lord your God will be with you wherever you go."
   },
   {
    "book": 45,
    "ref": "Romans 3:23",
    "context": "Paul levels the field: every person, same diagnosis.",
    "text": "for all have sinned and fall short of the glory of God,"
   },
   {
    "book": 49,
    "ref": "Ephesians 2:8-9",
    "context": "Salvation's source, means, and the boast it rules out.",
    "text": "For it is by grace you have been saved, through faith—and this not from yourselves, it is the gift of God— not by works, so that no one can boast."
   },
   {
    "book": 46,
    "ref": "1 Corinthians 13:4",
    "context": "The love chapter, read at more weddings than any other text.",
    "text": "Love is patient, love is kind. It does not envy, it does not boast, it is not proud."
   },
   {
    "book": 48,
    "ref": "Galatians 5:22-23",
    "context": "The fruit of the Spirit: nine traits, one harvest.",
    "text": "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law."
   },
   {
    "book": 19,
    "ref": "Psalm 119:105",
    "context": "From the longest chapter in the Bible, an ode to God's word.",
    "text": "נ Nun Your word is a lamp to my feet and a light for my path."
   },
   {
    "book": 43,
    "ref": "John 14:6",
    "context": "Jesus' answer to Thomas the night before the cross.",
    "text": "Jesus answered, I am the way and the truth and the life. No one comes to the Father except through me."
   },
   {
    "book": 40,
    "ref": "Matthew 6:33",
    "context": "From the Sermon on the Mount, on where worry should rank.",
    "text": "But seek first his kingdom and his righteousness, and all these things will be given to you as well."
   },
   {
    "book": 58,
    "ref": "Hebrews 11:1",
    "context": "The opening line of the Bible's hall of faith.",
    "text": "By Faith Now faith is being sure of what we hope for and certain of what we do not see."
   },
   {
    "book": 55,
    "ref": "2 Timothy 3:16",
    "context": "Paul's final letter, on where Scripture comes from.",
    "text": "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness,"
   },
   {
    "book": 62,
    "ref": "1 John 1:9",
    "context": "John's assurance for anyone who has blown it.",
    "text": "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness."
   },
   {
    "book": 66,
    "ref": "Revelation 3:20",
    "context": "Jesus knocking, in the letter to lukewarm Laodicea.",
    "text": "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with him, and he with me."
   },
   {
    "book": 19,
    "ref": "Psalm 46:1",
    "context": "The psalm behind Luther's hymn A Mighty Fortress.",
    "text": "God is our refuge and strength, an ever-present help in trouble."
   },
   {
    "book": 40,
    "ref": "Matthew 11:28",
    "context": "An open invitation to everyone worn out by life and religion.",
    "text": "Come to me, all you who are weary and burdened, and I will give you rest."
   },
   {
    "book": 45,
    "ref": "Romans 6:23",
    "context": "Wages versus gift: Paul's starkest contrast.",
    "text": "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord."
   }
  ]
 },
 {
  "label": "Familiar Ground",
  "verses": [
   {
    "book": 19,
    "ref": "Psalm 27:1",
    "context": "David: light, salvation, stronghold. So why be afraid?",
    "text": "The Lord is my light and my salvation— whom shall I fear? The Lord is the stronghold of my life— of whom shall I be afraid?"
   },
   {
    "book": 23,
    "ref": "Isaiah 41:10",
    "context": "Do not fear, with four promises attached.",
    "text": "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand."
   },
   {
    "book": 45,
    "ref": "Romans 12:2",
    "context": "The alternative to being squeezed into the world's mold.",
    "text": "Do not conform any longer to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is—his good, pleasing and perfect will."
   },
   {
    "book": 47,
    "ref": "2 Corinthians 5:17",
    "context": "What actually happens when someone comes to Christ.",
    "text": "Therefore, if anyone is in Christ, he is a new creation; the old has gone, the new has come!"
   },
   {
    "book": 20,
    "ref": "Proverbs 22:6",
    "context": "The classic proverb for parents.",
    "text": "Train a child in the way he should go, and when he is old he will not turn from it."
   },
   {
    "book": 5,
    "ref": "Deuteronomy 6:5",
    "context": "The Shema's command, which Jesus called the greatest.",
    "text": "Love the Lord your God with all your heart and with all your soul and with all your strength."
   },
   {
    "book": 60,
    "ref": "1 Peter 5:7",
    "context": "Peter's one-line cure for anxiety.",
    "text": "Cast all your anxiety on him because he cares for you."
   },
   {
    "book": 58,
    "ref": "Hebrews 4:12",
    "context": "Scripture described as a living, cutting blade.",
    "text": "For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart."
   },
   {
    "book": 50,
    "ref": "Philippians 4:6-7",
    "context": "Paul's prescription for anxiety, written from prison.",
    "text": "Do not be anxious about anything, but in everything, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus."
   },
   {
    "book": 43,
    "ref": "John 1:1",
    "context": "John opens his gospel where Genesis opens the Bible.",
    "text": "The Word Became Flesh In the beginning was the Word, and the Word was with God, and the Word was God."
   },
   {
    "book": 25,
    "ref": "Lamentations 3:22-23",
    "context": "Hope written in the rubble of Jerusalem.",
    "text": "Because of the Lord’s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness."
   },
   {
    "book": 19,
    "ref": "Psalm 121:1-2",
    "context": "A song for pilgrims climbing the road to Jerusalem.",
    "text": "I lift up my eyes to the hills— where does my help come from? My help comes from the Lord, the Maker of heaven and earth."
   },
   {
    "book": 19,
    "ref": "Psalm 139:14",
    "context": "David marvels at how he was made.",
    "text": "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well."
   },
   {
    "book": 23,
    "ref": "Isaiah 53:5",
    "context": "The suffering servant, seven centuries before the cross.",
    "text": "But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was upon him, and by his wounds we are healed."
   },
   {
    "book": 41,
    "ref": "Mark 10:45",
    "context": "Jesus defines greatness by pointing at his own mission.",
    "text": "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many."
   },
   {
    "book": 42,
    "ref": "Luke 1:37",
    "context": "Gabriel's word to Mary in Nazareth.",
    "text": "For nothing is impossible with God."
   },
   {
    "book": 44,
    "ref": "Acts 1:8",
    "context": "The risen Jesus' final promise before ascending.",
    "text": "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth."
   },
   {
    "book": 51,
    "ref": "Colossians 3:23",
    "context": "Work re-aimed: same tasks, different boss.",
    "text": "Whatever you do, work at it with all your heart, as working for the Lord, not for men,"
   },
   {
    "book": 52,
    "ref": "1 Thessalonians 5:16-18",
    "context": "Three habits Paul calls God's will for you.",
    "text": "Be joyful always; pray continually; give thanks in all circumstances, for this is God’s will for you in Christ Jesus."
   },
   {
    "book": 48,
    "ref": "Galatians 2:20",
    "context": "Paul's own testimony in a single sentence.",
    "text": "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave himself for me."
   },
   {
    "book": 49,
    "ref": "Ephesians 6:10-11",
    "context": "The opening bell of the armor-of-God passage.",
    "text": "The Armor of God Finally, be strong in the Lord and in his mighty power. Put on the full armor of God so that you can take your stand against the devil’s schemes."
   },
   {
    "book": 45,
    "ref": "Romans 10:9",
    "context": "Paul spells out how anyone is saved.",
    "text": "That if you confess with your mouth, Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved."
   },
   {
    "book": 40,
    "ref": "Matthew 5:16",
    "context": "Jesus tells his followers what their good works are for.",
    "text": "In the same way, let your light shine before men, that they may see your good deeds and praise your Father in heaven."
   },
   {
    "book": 59,
    "ref": "James 1:5",
    "context": "James on where to get wisdom, and how generously it's given.",
    "text": "If any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him."
   }
  ]
 },
 {
  "label": "Deeper Cuts",
  "verses": [
   {
    "book": 2,
    "ref": "Exodus 14:14",
    "context": "Moses at the Red Sea, with Egypt's army closing in.",
    "text": "The Lord will fight for you; you need only to be still."
   },
   {
    "book": 4,
    "ref": "Numbers 6:24-26",
    "context": "The blessing Aaron and his sons were told to speak over Israel.",
    "text": "‘The Lord bless you and keep you; the Lord make his face shine upon you and be gracious to you; the Lord turn his face toward you and give you peace.’"
   },
   {
    "book": 5,
    "ref": "Deuteronomy 31:6",
    "context": "Moses' farewell charge to Israel before the Jordan crossing.",
    "text": "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you."
   },
   {
    "book": 9,
    "ref": "1 Samuel 17:47",
    "context": "A shepherd boy to a giant, moments before the sling.",
    "text": "All those gathered here will know that it is not by sword or spear that the Lord saves; for the battle is the Lord’s, and he will give all of you into our hands."
   },
   {
    "book": 14,
    "ref": "2 Chronicles 7:14",
    "context": "God's reply to Solomon the night after the temple was dedicated.",
    "text": "if my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then will I hear from heaven and will forgive their sin and will heal their land."
   },
   {
    "book": 18,
    "ref": "Job 19:25",
    "context": "Job's defiant hope, spoken from the ash heap.",
    "text": "I know that my Redeemer lives, and that in the end he will stand upon the earth."
   },
   {
    "book": 19,
    "ref": "Psalm 37:4",
    "context": "From David's psalm on not fretting over the wicked.",
    "text": "Delight yourself in the Lord and he will give you the desires of your heart."
   },
   {
    "book": 20,
    "ref": "Proverbs 18:10",
    "context": "A proverb that pictures God's name as a fortress.",
    "text": "The name of the Lord is a strong tower; the righteous run to it and are safe."
   },
   {
    "book": 21,
    "ref": "Ecclesiastes 3:1",
    "context": "The opening of the Teacher's famous poem on seasons.",
    "text": "A Time for Everything There is a time for everything, and a season for every activity under heaven:"
   },
   {
    "book": 23,
    "ref": "Isaiah 26:3",
    "context": "A song of praise from the prophet's vision of the last days.",
    "text": "You will keep in perfect peace him whose mind is steadfast, because he trusts in you."
   },
   {
    "book": 24,
    "ref": "Jeremiah 17:7-8",
    "context": "The prophet's tree planted by the water.",
    "text": "But blessed is the man who trusts in the Lord, whose confidence is in him. He will be like a tree planted by the water that sends out its roots by the stream. It does not fear when heat comes; its leaves are always green. It has no worries in a year of drought and never fails to bear fruit."
   },
   {
    "book": 26,
    "ref": "Ezekiel 36:26",
    "context": "A promise to exiles: a transplant of the heart.",
    "text": "I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh."
   },
   {
    "book": 27,
    "ref": "Daniel 3:17-18",
    "context": "Three friends answer the king in front of the furnace.",
    "text": "If we are thrown into the blazing furnace, the God we serve is able to save us from it, and he will rescue us from your hand, O king. But even if he does not, we want you to know, O king, that we will not serve your gods or worship the image of gold you have set up."
   },
   {
    "book": 28,
    "ref": "Hosea 6:6",
    "context": "A verse Jesus quoted twice to the Pharisees.",
    "text": "For I desire mercy, not sacrifice, and acknowledgment of God rather than burnt offerings."
   },
   {
    "book": 29,
    "ref": "Joel 2:28",
    "context": "The prophecy Peter quoted at Pentecost.",
    "text": "The Day of the Lord And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams, your young men will see visions."
   },
   {
    "book": 30,
    "ref": "Amos 5:24",
    "context": "The shepherd-prophet's line made famous by Dr. King.",
    "text": "But let justice roll on like a river, righteousness like a never-failing stream!"
   },
   {
    "book": 32,
    "ref": "Jonah 2:2",
    "context": "A prayer prayed from inside a fish.",
    "text": "He said: In my distress I called to the Lord, and he answered me. From the depths of the grave I called for help, and you listened to my cry."
   },
   {
    "book": 35,
    "ref": "Habakkuk 3:17-18",
    "context": "The prophet's decision to rejoice with the barns empty.",
    "text": "Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls, yet I will rejoice in the Lord, I will be joyful in God my Savior."
   },
   {
    "book": 36,
    "ref": "Zephaniah 3:17",
    "context": "God pictured as singing over his people.",
    "text": "The Lord your God is with you, he is mighty to save. He will take great delight in you, he will quiet you with his love, he will rejoice over you with singing."
   },
   {
    "book": 39,
    "ref": "Malachi 3:10",
    "context": "The last book of the Old Testament, on tithes and floodgates.",
    "text": "Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the Lord Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that you will not have room enough for it."
   },
   {
    "book": 40,
    "ref": "Matthew 5:14",
    "context": "From the Sermon on the Mount: a city on a hill.",
    "text": "You are the light of the world. A city on a hill cannot be hidden."
   },
   {
    "book": 42,
    "ref": "Luke 6:31",
    "context": "The Golden Rule, in Jesus' own words.",
    "text": "Do to others as you would have them do to you."
   },
   {
    "book": 43,
    "ref": "John 13:34-35",
    "context": "A new command, given right after Jesus washed feet.",
    "text": "A new command I give you: Love one another. As I have loved you, so you must love one another. By this all men will know that you are my disciples, if you love one another."
   },
   {
    "book": 56,
    "ref": "Titus 3:5",
    "context": "Paul reminding a young pastor on Crete how salvation works.",
    "text": "he saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit,"
   }
  ]
 },
 {
  "label": "Off the Path",
  "verses": [
   {
    "book": 1,
    "ref": "Genesis 50:20",
    "context": "Joseph to the brothers who sold him, decades later.",
    "text": "You intended to harm me, but God intended it for good to accomplish what is now being done, the saving of many lives."
   },
   {
    "book": 3,
    "ref": "Leviticus 19:18",
    "context": "The second-greatest commandment, tucked inside the holiness code.",
    "text": "‘Do not seek revenge or bear a grudge against one of your people, but love your neighbor as yourself. I am the Lord."
   },
   {
    "book": 6,
    "ref": "Joshua 24:15",
    "context": "Joshua's last speech to Israel at Shechem.",
    "text": "But if serving the Lord seems undesirable to you, then choose for yourselves this day whom you will serve, whether the gods your forefathers served beyond the River, or the gods of the Amorites, in whose land you are living. But as for me and my household, we will serve the Lord."
   },
   {
    "book": 8,
    "ref": "Ruth 2:12",
    "context": "Boaz's blessing over a Moabite widow gleaning his field.",
    "text": "May the Lord repay you for what you have done. May you be richly rewarded by the Lord, the God of Israel, under whose wings you have come to take refuge."
   },
   {
    "book": 11,
    "ref": "1 Kings 18:21",
    "context": "Elijah's challenge to the crowd on Mount Carmel.",
    "text": "Elijah went before the people and said, How long will you waver between two opinions? If the Lord is God, follow him; but if Baal is God, follow him. But the people said nothing."
   },
   {
    "book": 12,
    "ref": "2 Kings 6:16",
    "context": "Elisha calms his servant, surrounded by an army.",
    "text": "Don’t be afraid, the prophet answered. Those who are with us are more than those who are with them."
   },
   {
    "book": 13,
    "ref": "1 Chronicles 16:11",
    "context": "From David's song when the ark came to Jerusalem.",
    "text": "Look to the Lord and his strength; seek his face always."
   },
   {
    "book": 15,
    "ref": "Ezra 3:11",
    "context": "The second temple's foundation is laid, to shouts and weeping.",
    "text": "With praise and thanksgiving they sang to the Lord: He is good; his love to Israel endures forever. And all the people gave a great shout of praise to the Lord, because the foundation of the house of the Lord was laid."
   },
   {
    "book": 17,
    "ref": "Esther 4:14",
    "context": "Mordecai's message to a queen inside the palace.",
    "text": "For if you remain silent at this time, relief and deliverance for the Jews will arise from another place, but you and your father’s family will perish. And who knows but that you have come to royal position for such a time as this?"
   },
   {
    "book": 18,
    "ref": "Job 42:2",
    "context": "Job's reply after God speaks from the storm.",
    "text": "I know that you can do all things; no plan of yours can be thwarted."
   },
   {
    "book": 19,
    "ref": "Psalm 90:12",
    "context": "From the only psalm attributed to Moses.",
    "text": "Teach us to number our days aright, that we may gain a heart of wisdom."
   },
   {
    "book": 20,
    "ref": "Proverbs 16:9",
    "context": "Planning versus providence, in one line.",
    "text": "In his heart a man plans his course, but the Lord determines his steps."
   },
   {
    "book": 21,
    "ref": "Ecclesiastes 12:13",
    "context": "The Teacher's final conclusion.",
    "text": "Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the whole duty of man."
   },
   {
    "book": 22,
    "ref": "Song of Songs 8:7",
    "context": "The Song's climactic word on love and floods.",
    "text": "Many waters cannot quench love; rivers cannot wash it away. If one were to give all the wealth of his house for love, it would be utterly scorned."
   },
   {
    "book": 23,
    "ref": "Isaiah 55:8-9",
    "context": "God on the gap between his thoughts and ours.",
    "text": "For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord. As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts."
   },
   {
    "book": 24,
    "ref": "Jeremiah 31:3",
    "context": "Everlasting love, promised to a nation headed for exile.",
    "text": "The Lord appeared to us in the past, saying: I have loved you with an everlasting love; I have drawn you with loving-kindness."
   },
   {
    "book": 26,
    "ref": "Ezekiel 37:4-5",
    "context": "Prophesying to a valley of dry bones.",
    "text": "Then he said to me, Prophesy to these bones and say to them, ‘Dry bones, hear the word of the Lord! This is what the Sovereign Lord says to these bones: I will make breath enter you, and you will come to life."
   },
   {
    "book": 34,
    "ref": "Nahum 1:7",
    "context": "A tender line in a book that is mostly about Nineveh's doom.",
    "text": "The Lord is good, a refuge in times of trouble. He cares for those who trust in him,"
   },
   {
    "book": 38,
    "ref": "Zechariah 4:6",
    "context": "A word to Zerubbabel about rebuilding the temple.",
    "text": "So he said to me, This is the word of the Lord to Zerubbabel: ‘Not by might nor by power, but by my Spirit,’ says the Lord Almighty."
   },
   {
    "book": 40,
    "ref": "Matthew 16:24",
    "context": "Jesus, right after Peter's confession at Caesarea Philippi.",
    "text": "Then Jesus said to his disciples, If anyone would come after me, he must deny himself and take up his cross and follow me."
   },
   {
    "book": 44,
    "ref": "Acts 20:35",
    "context": "A saying of Jesus preserved nowhere in the four Gospels.",
    "text": "In everything I did, I showed you that by this kind of hard work we must help the weak, remembering the words the Lord Jesus himself said: ‘It is more blessed to give than to receive.’"
   },
   {
    "book": 54,
    "ref": "1 Timothy 6:6",
    "context": "Paul to Timothy on gain of a different kind.",
    "text": "But godliness with contentment is great gain."
   },
   {
    "book": 60,
    "ref": "1 Peter 3:15",
    "context": "Peter's charge to be ready with an answer.",
    "text": "But in your hearts set apart Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect,"
   },
   {
    "book": 65,
    "ref": "Jude 24-25",
    "context": "The doxology that closes one of the Bible's shortest letters.",
    "text": "Doxology To him who is able to keep you from falling and to present you before his glorious presence without fault and with great joy— to the only God our Savior be glory, majesty, power and authority, through Jesus Christ our Lord, before all ages, now and forevermore! Amen."
   }
  ]
 },
 {
  "label": "Deep Wells",
  "verses": [
   {
    "book": 1,
    "ref": "Genesis 28:15",
    "context": "God's promise to Jacob at Bethel, asleep on a stone.",
    "text": "I am with you and will watch over you wherever you go, and I will bring you back to this land. I will not leave you until I have done what I have promised you."
   },
   {
    "book": 2,
    "ref": "Exodus 33:14",
    "context": "God's reply when Moses refused to go on without him.",
    "text": "The Lord replied, My Presence will go with you, and I will give you rest."
   },
   {
    "book": 4,
    "ref": "Numbers 23:19",
    "context": "Balaam, hired to curse Israel, blesses them instead.",
    "text": "God is not a man, that he should lie, nor a son of man, that he should change his mind. Does he speak and then not act? Does he promise and not fulfill?"
   },
   {
    "book": 5,
    "ref": "Deuteronomy 30:19",
    "context": "Moses sets the choice before Israel on the plains of Moab.",
    "text": "This day I call heaven and earth as witnesses against you that I have set before you life and death, blessings and curses. Now choose life, so that you and your children may live"
   },
   {
    "book": 7,
    "ref": "Judges 21:25",
    "context": "The last verse of Judges, and its whole diagnosis.",
    "text": "In those days Israel had no king; everyone did as he saw fit."
   },
   {
    "book": 10,
    "ref": "2 Samuel 22:31",
    "context": "David's song of deliverance, near the end of his life.",
    "text": "As for God, his way is perfect; the word of the Lord is flawless. He is a shield for all who take refuge in him."
   },
   {
    "book": 14,
    "ref": "2 Chronicles 16:9",
    "context": "Hanani the seer rebukes King Asa.",
    "text": "For the eyes of the Lord range throughout the earth to strengthen those whose hearts are fully committed to him. You have done a foolish thing, and from now on you will be at war."
   },
   {
    "book": 18,
    "ref": "Job 23:10",
    "context": "Job, mid-argument, still trusting the outcome.",
    "text": "But he knows the way that I take; when he has tested me, I will come forth as gold."
   },
   {
    "book": 19,
    "ref": "Psalm 62:1-2",
    "context": "David: rest, rock, salvation, fortress.",
    "text": "My soul finds rest in God alone; my salvation comes from him. He alone is my rock and my salvation; he is my fortress, I will never be shaken."
   },
   {
    "book": 20,
    "ref": "Proverbs 27:17",
    "context": "Iron sharpening iron.",
    "text": "As iron sharpens iron, so one man sharpens another."
   },
   {
    "book": 21,
    "ref": "Ecclesiastes 4:9-10",
    "context": "The Teacher on why two beat one.",
    "text": "Two are better than one, because they have a good return for their work: If one falls down, his friend can help him up. But pity the man who falls and has no one to help him up!"
   },
   {
    "book": 23,
    "ref": "Isaiah 43:2",
    "context": "Promises for the waters and the fire.",
    "text": "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze."
   },
   {
    "book": 24,
    "ref": "Jeremiah 33:3",
    "context": "Spoken to the prophet while he was confined in the courtyard of the guard.",
    "text": "‘Call to me and I will answer you and tell you great and unsearchable things you do not know.’"
   },
   {
    "book": 25,
    "ref": "Lamentations 3:25-26",
    "context": "Quiet waiting, from a book of tears.",
    "text": "The Lord is good to those whose hope is in him, to the one who seeks him; it is good to wait quietly for the salvation of the Lord."
   },
   {
    "book": 27,
    "ref": "Daniel 12:3",
    "context": "Daniel's final chapter, on those who shine like stars.",
    "text": "Those who are wise will shine like the brightness of the heavens, and those who lead many to righteousness, like the stars for ever and ever."
   },
   {
    "book": 33,
    "ref": "Micah 6:8",
    "context": "The prophet's summary of what God actually requires.",
    "text": "He has showed you, O man, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God."
   },
   {
    "book": 35,
    "ref": "Habakkuk 2:14",
    "context": "A promise tucked among five woes against Babylon.",
    "text": "For the earth will be filled with the knowledge of the glory of the Lord, as the waters cover the sea."
   },
   {
    "book": 37,
    "ref": "Haggai 1:5",
    "context": "The prophet's refrain to a people who had stopped building.",
    "text": "Now this is what the Lord Almighty says: Give careful thought to your ways."
   },
   {
    "book": 38,
    "ref": "Zechariah 9:9",
    "context": "The Palm Sunday prophecy, five centuries early.",
    "text": "The Coming of Zion’s King Rejoice greatly, O Daughter of Zion! Shout, Daughter of Jerusalem! See, your king comes to you, righteous and having salvation, gentle and riding on a donkey, on a colt, the foal of a donkey."
   },
   {
    "book": 46,
    "ref": "1 Corinthians 10:13",
    "context": "Paul on temptation and the way out.",
    "text": "No temptation has seized you except what is common to man. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can stand up under it."
   },
   {
    "book": 47,
    "ref": "2 Corinthians 12:9",
    "context": "God's answer to Paul's thorn.",
    "text": "But he said to me, My grace is sufficient for you, for my power is made perfect in weakness. Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me."
   },
   {
    "book": 57,
    "ref": "Philemon 6",
    "context": "Paul's prayer for a slave owner in Colossae.",
    "text": "I pray that you may be active in sharing your faith, so that you will have a full understanding of every good thing we have in Christ."
   },
   {
    "book": 64,
    "ref": "3 John 4",
    "context": "The elder's greatest joy, in one of the Bible's shortest books.",
    "text": "I have no greater joy than to hear that my children are walking in the truth."
   },
   {
    "book": 58,
    "ref": "Hebrews 13:8",
    "context": "One line on the unchanging Christ, near the end of Hebrews.",
    "text": "Jesus Christ is the same yesterday and today and forever."
   }
  ]
 }
];
